name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin 056449379091.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t otel-php-app .

    - name: Tag Image
      run: docker tag otel-php-app:latest 056449379091.dkr.ecr.us-east-1.amazonaws.com/otel-php-app:latest

    - name: Push Image to ECR
      run: docker push 056449379091.dkr.ecr.us-east-1.amazonaws.com/otel-php-app:latest

    - name: Force ECS Deployment
      run: |
        aws ecs update-service \
          --cluster otel-cluster \
          --service otel-service \
          --force-new-deployment
